// Nombre de lengua en Wikcionario (inglés) → [categoría del juego, variante a mostrar | null].
// null = paso que se omite (el propio español). Las protolenguas (Proto-…) cortan la cadena en 2-candidatas.mjs.
export const LENGUAS_WIKI = {
  'Old Spanish': null, 'Spanish': null, 'Medieval Spanish': null,
  'Latin': ['latín', null], 'Classical Latin': ['latín', null], 'Late Latin': ['latín', 'latín tardío'],
  'Vulgar Latin': ['latín', 'latín vulgar'], 'Medieval Latin': ['latín', 'latín medieval'], 'Early Medieval Latin': ['latín', 'latín medieval'],
  'Ecclesiastical Latin': ['latín', 'latín eclesiástico'], 'New Latin': ['latín', 'latín moderno'], 'Modern Latin': ['latín', 'latín moderno'],
  'Old Latin': ['latín', 'latín arcaico'], 'Renaissance Latin': ['latín', 'latín renacentista'], 'Contemporary Latin': ['latín', 'latín moderno'],
  'Ancient Greek': ['griego', null], 'Koine Greek': ['griego', 'griego koiné'], 'Byzantine Greek': ['griego', 'griego bizantino'],
  'Medieval Greek': ['griego', 'griego bizantino'], 'Greek': ['griego', 'griego moderno'], 'Mycenaean Greek': ['griego', 'griego micénico'], 'Doric Greek': ['griego', 'griego dórico'], 'Epic Greek': ['griego', 'griego homérico'], 'Attic Greek': ['griego', 'griego ático'], 'Ionic Greek': ['griego', 'griego jónico'],
  'Arabic': ['árabe', null], 'Classical Arabic': ['árabe', 'árabe clásico'], 'Andalusian Arabic': ['árabe', 'árabe hispánico'], 'Maghrebi Arabic': ['árabe', 'árabe magrebí'], 'Moroccan Arabic': ['árabe', 'árabe marroquí'], 'Egyptian Arabic': ['árabe', 'árabe egipcio'],
  'Frankish': ['germánico', 'fráncico'], 'Gothic': ['germánico', 'gótico'], 'Old Norse': ['germánico', 'nórdico antiguo'], 'Old High German': ['germánico', 'alto alemán antiguo'],
  'Lombardic': ['germánico', 'longobardo'], 'Old Saxon': ['germánico', 'sajón antiguo'], 'Suevic': ['germánico', 'suevo'], 'Burgundian': ['germánico', 'burgundio'], 'Old Low Franconian': ['germánico', 'franconio antiguo'],
  'Old English': ['inglés', 'inglés antiguo'], 'Middle English': ['inglés', 'inglés medio'], 'English': ['inglés', null], 'American English': ['inglés', 'inglés americano'], 'British English': ['inglés', 'inglés británico'], 'Scots': ['inglés', 'escocés'],
  'German': ['alemán', null], 'Middle High German': ['alemán', 'alto alemán medio'], 'Low German': ['alemán', 'bajo alemán'], 'Middle Low German': ['alemán', 'bajo alemán medio'], 'Swiss German': ['alemán', 'alemán suizo'], 'Yiddish': ['yidis', null],
  'Dutch': ['neerlandés', null], 'Middle Dutch': ['neerlandés', 'neerlandés medio'], 'Afrikaans': ['neerlandés', 'afrikáans'],
  'Swedish': ['nórdico', 'sueco'], 'Norwegian': ['nórdico', 'noruego'], 'Danish': ['nórdico', 'danés'], 'Icelandic': ['nórdico', 'islandés'], 'Norwegian Bokmål': ['nórdico', 'noruego'],
  'French': ['francés', null], 'Old French': ['francés', 'francés antiguo'], 'Middle French': ['francés', 'francés medio'], 'Anglo-Norman': ['francés', 'anglonormando'], 'Norman': ['francés', 'normando'], 'Picard': ['francés', 'picardo'],
  'Occitan': ['occitano', null], 'Old Occitan': ['occitano', 'occitano antiguo'], 'Provençal': ['occitano', 'provenzal'], 'Old Provençal': ['occitano', 'provenzal antiguo'], 'Gascon': ['occitano', 'gascón'],
  'Catalan': ['catalán', null], 'Old Catalan': ['catalán', 'catalán antiguo'], 'Valencian': ['catalán', 'valenciano'],
  'Portuguese': ['portugués', null], 'Old Portuguese': ['portugués', 'galaicoportugués'], 'Galician-Portuguese': ['portugués', 'galaicoportugués'], 'Galician': ['gallego', null], 'Brazilian Portuguese': ['portugués', 'portugués de Brasil'],
  'Italian': ['italiano', null], 'Old Italian': ['italiano', 'italiano antiguo'], 'Venetian': ['italiano', 'veneciano'], 'Genoese': ['italiano', 'genovés'], 'Ligurian': ['italiano', 'ligur'],
  'Neapolitan': ['italiano', 'napolitano'], 'Sicilian': ['italiano', 'siciliano'], 'Tuscan': ['italiano', 'toscano'], 'Lombard': ['italiano', 'lombardo'], 'Old Tuscan': ['italiano', 'toscano antiguo'], 'Sardinian': ['sardo', null],
  'Romanian': ['rumano', null], 'Mozarabic': ['mozárabe', null], 'Asturian': ['asturleonés', 'asturiano'], 'Leonese': ['asturleonés', 'leonés'], 'Aragonese': ['aragonés', null], 'Ladino': ['judeoespañol', null],
  'Basque': ['vasco', null], 'Gaulish': ['celta', 'galo'], 'Celtiberian': ['celta', 'celtíbero'], 'Old Irish': ['celta', 'irlandés antiguo'], 'Irish': ['celta', 'irlandés'], 'Welsh': ['celta', 'galés'], 'Breton': ['celta', 'bretón'], 'Scottish Gaelic': ['celta', 'gaélico escocés'], 'Iberian': ['ibero', null],
  'Etruscan': ['etrusco', null], 'Oscan': ['osco', null], 'Umbrian': ['umbro', null],
  'Hebrew': ['hebreo', null], 'Biblical Hebrew': ['hebreo', 'hebreo bíblico'], 'Medieval Hebrew': ['hebreo', 'hebreo medieval'], 'Mishnaic Hebrew': ['hebreo', 'hebreo misnaico'],
  'Aramaic': ['arameo', null], 'Classical Syriac': ['arameo', 'siríaco'], 'Imperial Aramaic': ['arameo', 'arameo imperial'], 'Jewish Aramaic': ['arameo', 'arameo judío'], 'Syriac': ['arameo', 'siríaco'],
  'Akkadian': ['acadio', null], 'Sumerian': ['sumerio', null], 'Phoenician': ['fenicio', null], 'Punic': ['fenicio', 'púnico'], 'Egyptian': ['egipcio', null], 'Coptic': ['egipcio', 'copto'], 'Demotic Egyptian': ['egipcio', 'egipcio demótico'],
  'Persian': ['persa', null], 'Middle Persian': ['persa', 'persa medio'], 'Old Persian': ['persa', 'persa antiguo'], 'Classical Persian': ['persa', 'persa clásico'], 'Parthian': ['persa', 'parto'], 'Avestan': ['persa', 'avéstico'], 'Sogdian': ['persa', 'sogdiano'],
  'Sanskrit': ['sánscrito', null], 'Pali': ['sánscrito', 'pali'], 'Prakrit': ['sánscrito', 'prácrito'], 'Gandhari': ['sánscrito', 'gandhari'],
  'Hindi': ['hindi', null], 'Hindustani': ['hindi', 'indostánico'], 'Urdu': ['hindi', 'urdu'], 'Bengali': ['bengalí', null], 'Marathi': ['maratí', null],
  'Tamil': ['tamil', null], 'Malayalam': ['malayalam', null], 'Kannada': ['canarés', null], 'Telugu': ['telugu', null],
  'Turkish': ['turco', null], 'Ottoman Turkish': ['turco', 'turco otomano'], 'Old Turkic': ['turco', 'túrquico antiguo'], 'Chagatai': ['turco', 'chagatai'], 'Tatar': ['turco', 'tártaro'], 'Kazakh': ['turco', 'kazajo'], 'Old Anatolian Turkish': ['turco', 'turco anatolio antiguo'],
  'Russian': ['ruso', null], 'Polish': ['polaco', null], 'Czech': ['checo', null], 'Old Czech': ['checo', 'checo antiguo'], 'Serbo-Croatian': ['serbocroata', null], 'Hungarian': ['húngaro', null], 'Finnish': ['finés', null], 'Sami': ['sami', null], 'Northern Sami': ['sami', null],
  'Japanese': ['japonés', null], 'Chinese': ['chino', null], 'Mandarin': ['chino', 'mandarín'], 'Cantonese': ['chino', 'cantonés'], 'Hokkien': ['chino', 'hokkien'], 'Min Nan': ['chino', 'min nan'], 'Middle Chinese': ['chino', 'chino medio'], 'Old Chinese': ['chino', 'chino antiguo'], 'Korean': ['coreano', null],
  'Malay': ['malayo', null], 'Classical Malay': ['malayo', 'malayo clásico'], 'Tagalog': ['tagalo', null], 'Javanese': ['javanés', null], 'Cebuano': ['cebuano', null],
  'Tongan': ['polinesio', 'tongano'], 'Maori': ['polinesio', 'maorí'], 'Hawaiian': ['polinesio', 'hawaiano'], 'Tahitian': ['polinesio', 'tahitiano'], 'Samoan': ['polinesio', 'samoano'],
  'Classical Nahuatl': ['náhuatl', null], 'Nahuatl': ['náhuatl', null], 'Quechua': ['quechua', null], 'Classical Quechua': ['quechua', null], 'Aymara': ['aimara', null],
  'Taíno': ['taíno', null], 'Carib': ['caribe', null], 'Arawak': ['arahuaco', null], 'Old Tupi': ['tupí', null], 'Tupi': ['tupí', null], 'Guarani': ['guaraní', null], 'Old Guarani': ['guaraní', null],
  'Mapudungun': ['mapuche', null], 'Yucatec Maya': ['maya', 'maya yucateco'], 'Mayan': ['maya', null], 'Cumanagoto': ['caribe', 'cumanagoto'], 'Otomi': ['otomí', null],
  'Kimbundu': ['bantú', 'kimbundu'], 'Kikongo': ['bantú', 'kikongo'], 'Kongo': ['bantú', 'kikongo'], 'Swahili': ['bantú', 'suajili'], 'Wolof': ['wólof', null], 'Mandinka': ['mandinga', null], 'Yoruba': ['yoruba', null],
  'Tibetan': ['tibetano', null], 'Mongolian': ['mongol', null], 'Middle Mongol': ['mongol', 'mongol medio'], 'Inuktitut': ['inuit', null], 'Greenlandic': ['inuit', 'groenlandés'], 'Tamazight': ['bereber', null], 'Berber': ['bereber', null], 'Guanche': ['bereber', 'guanche'],
  'Armenian': ['armenio', null], 'Georgian': ['georgiano', null], 'Albanian': ['albanés', null], 'Lithuanian': ['lituano', null], 'Esperanto': ['esperanto', null],
}
